//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheshmebazarIrMyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.PurchaseCarts = new HashSet<PurchaseCart>();
            this.SliderForProviders = new HashSet<SliderForProvider>();
        }
    
        public int Id { get; set; }
        public string Family { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Txt { get; set; }
        public string PhoneOne { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<bool> AdminConfirm { get; set; }
        public string User_id { get; set; }
        public byte[] Logo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseCart> PurchaseCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SliderForProvider> SliderForProviders { get; set; }
    }
}
