//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheshmebazarIrMyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseCart
    {
        public int Id { get; set; }
        public Nullable<int> Store_Id { get; set; }
        public Nullable<int> Package_Id { get; set; }
        public Nullable<System.DateTime> DateOfPay { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string User_Id { get; set; }
        public string Token { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
