//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheshmebazarIrMyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderForProvider
    {
        public int Id { get; set; }
        public Nullable<int> Provider_Id { get; set; }
        public byte[] Pic { get; set; }
        public Nullable<System.DateTime> CreateOrEditdate { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
